version: '2'


services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "35000:6000"
    links:
      - db

  front:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: front
    ports:
      - "80:6000"
    links:
      - back

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    command: mongod

volumes:
  mongodb:
  mongodb_config: